apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  name: survey
  namespace: argocd1
spec:
  replicas: 5
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
      namespace: argocd1
    spec:
      containers:
        - image: njogani/swe645_hw2:202311270456
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 8080
              name: survey
              protocol: TCP
          resources: {}
status:
  availableReplicas: 5
  observedGeneration: 20
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
