apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: >-
      [{"addresses":["172.31.62.250"],"port":30892,"protocol":"TCP","serviceName":"hw2:springboot-hw3","allNodes":true}]
  creationTimestamp: '2023-11-28T01:28:58Z'
  name: springboot-hw3
  namespace: argocd1
spec:
  ports:
    - nodePort: 30892
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}