apiVersion: v1
kind: Service
metadata:
  name: springboot-hw3
  namespace: argocd1
spec:
  ports:
    - nodePort: 30892
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
