apiVersion: v1
kind: Service
metadata:
  name: survey-clusterip
  namespace: argocd1
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-hw2-survey
  ports:
    - protocol: TCP
      port: 8080  # This should match the containerPort of your deployment
      targetPort: 8080  # This should match the containerPort of your deployment
  type: ClusterIP
